version: '3.3'
services:
  mysql:
   container_name: spring_mvc_hibernate_mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_DATABASE: spring_hibernate
    MYSQL_PASSWORD: root
   ports:
   - "3307:3306"
   restart: always
  
  app:
    restart: always
    build: .
    ports:
     - 8080:8080
    depends_on:
      - mysql